// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Cards(choice string, cards []string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		for _, card := range cards {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<li class=\"flex flex-col items-center p-8 rounded-lg hover:scale-110 bg-[#7AA2E3] cursor-pointer\" onclick=\"document.getElementById(&#39;pngFile&#39;).click();\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if choice == "image" {
				templ_7745c5c3_Err = imageSVG().Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else if choice == "document" {
				templ_7745c5c3_Err = documentSVG().Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else if choice == "audio" {
				templ_7745c5c3_Err = audioSVG().Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else if choice == "video" {
				templ_7745c5c3_Err = videoSVG().Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<p class=\"text-[#f8f6e3] font-bold text-4xl\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(card)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/components/cards.templ`, Line: 18, Col: 54}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p><input type=\"file\" accept=\"image/png\" id=\"pngFile\" name=\"file\" onchange=\"submitForm(&#39;pngFile&#39;)\" hidden></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script>\n\tfunction submitForm(fileInputId) {\n\t\tvar form = document.createElement('form');\n\t\tform.method = 'POST';\n\t\tform.enctype = 'multipart/form-data';\n\t\tform.style.display = 'none';\n\n\t\tif (fileInputId === 'pngFile') {\n\t\t\tform.action = '/shrink/png';\n\t\t} else if (fileInputId === 'jpgFile') {\n\t\t\tform.action = '/shrink/jpg';\n\t\t} else if (fileInputId === 'pdfFile') {\n\t\t\tform.action = '/shrink/pdf'\n\t\t} else if (fileInputId === 'docxFile') {\n\t\t\tform.action = '/shrink/docx';\n\t\t}\n\n\t\tvar fileInput = document.getElementById(fileInputId);\n\t\tform.appendChild(fileInput.cloneNode(true));\n\n\t\tdocument.body.appendChild(form);\n\t\tform.submit();\n\t\tdocument.body.removeChild(form);\n\t}\n</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
