// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func imageSVG() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<svg xmlns=\"http://www.w3.org/2000/svg\" xml:space=\"preserve\" width=\"128\" height=\"128\" style=\"shape-rendering:geometricPrecision;text-rendering:geometricPrecision;image-rendering:optimizeQuality;fill-rule:evenodd;clip-rule:evenodd\" viewBox=\"0 0 6.827 6.827\"><defs><style>\n\t\t\t.fil0 {\n\t\t\t\tfill: #F8F6E3;\n\t\t\t\tfill-rule: nonzero\n\t\t\t}\n\t\t</style></defs> <g id=\"Layer_x0020_1\"><g id=\"_554253040\"><path id=\"_554253832\" class=\"fil0\" d=\"M1.027 1.4H5.8c.048 0 .091.02.122.05v.001a.173.173 0 0 1 .051.122v3.68a.173.173 0 0 1-.173.173H1.027a.173.173 0 0 1-.174-.173v-3.68a.173.173 0 0 1 .173-.173zm4.733.213H1.067v3.6H5.76v-3.6z\"></path> <path id=\"_554253304\" class=\"fil0\" d=\"M1.326 4.618a.107.107 0 0 0 .151.15l1.311-1.31.992.99a.107.107 0 0 0 .15-.15L2.864 3.232a.107.107 0 0 0-.151 0L1.326 4.617z\"></path> <path id=\"_554253592\" class=\"fil0\" d=\"M3.3 3.818a.107.107 0 0 0 .15.15l.908-.907.992.991a.107.107 0 0 0 .15-.15L4.434 2.834a.107.107 0 0 0-.151 0l-.983.983z\"></path> <path id=\"_554253280\" class=\"fil0\" d=\"M2.148 2.027a.532.532 0 0 1 .377.91.532.532 0 0 1-.91-.377.532.532 0 0 1 .533-.533zm.227.307a.319.319 0 0 0-.547.226.319.319 0 0 0 .547.226.319.319 0 0 0 0-.452z\"></path></g></g> <path style=\"fill:none\" d=\"M0 0h6.827v6.827H0z\"></path></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
