// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func videoSVG() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"128\" height=\"128\" xml:space=\"preserve\"><path fill=\"#F8F6E3\" d=\"M127.756 99.109H.327V10.553h127.429v88.556zm-123.429-4h119.429V14.553H4.327v80.556z\"></path> <path fill=\"#F8F6E3\" d=\"M55.22 68.986v-28.15l24.095 14.075L55.22 68.986zm4-21.181v14.211l12.164-7.105-12.164-7.106zM19.357 107.865h11.295v4H19.357zM43.175 107.865h71.05v4h-71.05zM120.712 107.865H128v4h-7.288zM0 105.148h4v9.433H0zM7.714 105.148h4v9.433h-4z\"></path> <path fill=\"#F8F6E3\" d=\"M37.034 117.447c-4.146 0-7.518-3.401-7.518-7.582s3.373-7.582 7.518-7.582 7.518 3.401 7.518 7.582-3.373 7.582-7.518 7.582zm0-11.164c-1.94 0-3.518 1.606-3.518 3.582s1.578 3.582 3.518 3.582c1.939 0 3.518-1.606 3.518-3.582s-1.578-3.582-3.518-3.582zM64.041 84.148c-15.991 0-29-13.152-29-29.318s13.009-29.318 29-29.318c15.99 0 29 13.152 29 29.318s-13.01 29.318-29 29.318zm0-54.636c-13.785 0-25 11.357-25 25.318s11.215 25.318 25 25.318 25-11.357 25-25.318-11.215-25.318-25-25.318z\"></path></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
